### ISSUE TITLE
network-util doesn't handle NULL values

### ISSUE THREAD

**Issue by atmathis** [redcanaryco/redcanary-response-utils#12]
Issue encountered when when apparent null value is collected by the network-util. Error message below (1200 into 5000+ results processed). 

Traceback (most recent call last):
  File "network-util.py", line 370, in <module>
    sys.exit(main())
  File "network-util.py", line 357, in main
    domain=args.domain)
  File "network-util.py", line 158, in process_search
    dst_ip = ipaddress.ip_address(netconn.remote_ip)
  File "/usr/lib/python3.5/ipaddress.py", line 54, in ip_address
    address)
ValueError: '' does not appear to be an IPv4 or IPv6 address

**Comment by crahan** [comment]
Hi @atmathis, I've submitted a pull request to help fix this issue here: https://github.com/redcanaryco/redcanary-response-utils/pull/15
