### ISSUE TITLE
Response Tools - Doesn't Properly Handle Unicode, Cyrillic

### ISSUE THREAD

**Issue by Rhodochrosite** [redcanaryco/redcanary-response-utils#20]
Upon parsing command lines with Cyrillic Characters, the timeline.py fails to write the output properly.

```
Traceback (most recent call last):
  File ".\timeline.py", line 240, in <module>
    sys.exit(main())
  File ".\timeline.py", line 233, in main
    writer.writerow(row)
  File "C:\Program Files\Python\Python37\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 135-146: character maps to <undefined>

```

We were able to overcome this by changing the file open to pass the encoding argument.

[file = open(filename, file_mode)](https://github.com/redcanaryco/redcanary-response-utils/blob/master/timeline.py#L200)
 
`file = open(filename, file_mode, encoding="utf-8")`

Not sure if that is the correct fix or what other tools or detections are affected by the inability to handle Cryrillic characters.

Thank you.

Спасибо :)

**Comment by Rhodochrosite** [comment]
This is a duplicate of #10
