### ISSUE TITLE
network-util.py creates error

### ISSUE THREAD

**Issue by mxspeedy** [redcanaryco/redcanary-response-utils#6]
I get the following error executing the network-util.py anyone else with this issue?

~/api/redcanary-response-utils# ./network-util.py 
QUERY:  netconn_count:[1 TO *]
RESULT COUNT: 393
Traceback (most recent call last):
  File "./network-util.py", line 370, in <module>
    sys.exit(main())
  File "./network-util.py", line 357, in main
    domain=args.domain)
  File "./network-util.py", line 158, in process_search
    dst_ip = ipaddress.ip_address(netconn.remote_ip)
  File "/usr/lib/python2.7/dist-packages/ipaddress.py", line 166, in ip_address
    address)
ValueError: u'' does not appear to be an IPv4 or IPv6 address

**Comment by jksecurity** [comment]
Hello,

I can confirm that I got the same error today. It seems there are cases where the destination ip address is empty according to CB.

For the time being I removed all lines related to the ipaddress module as I do not rely on filtering of local addresses etc.

**Comment by jksecurity** [comment]
Hi,

I can confirm that the remote ip (destination ip) is empty for connections that go through a proxy. In that case the domain, proxy_ip and proxy_port fields are filled in.

Jerome

**Comment by Articho28** [comment]
Hi, I also get the error mentioned above. What should I do? 

Thank you.
